# Generated by Django 3.1.8 on 2021-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClesRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_de_derniere_modification', models.DateTimeField(auto_now=True)),
                ('semaine_de_vaccination', models.PositiveSmallIntegerField()),
                ('clef_repartition', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
