# Generated by Django 3.1.8 on 2021-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cles_region', '0001_initial'),
        ('vaccin', '0001_initial'),
        ('doses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clesregion',
            name='vaccins',
            field=models.ManyToManyField(through='doses.DosesRegion', to='vaccin.Vaccin'),
        ),
    ]
