# Generated by Django 3.1.8 on 2021-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
