# Generated by Django 3.1.8 on 2021-04-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('cles_departement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cles_departement.clesdepartement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
