# Generated by Django 3.1.8 on 2021-04-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cles_region', '__first__'),
        ('cles_departement', '__first__'),
        ('accounts', '0002_customuser_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cles_region.clesregion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cles_departement.clesdepartement'),
        ),
    ]
