# Generated by Django 3.1.8 on 2021-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreAmbulatoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('capacite', models.PositiveSmallIntegerField(default=0)),
                ('code_postal', models.PositiveSmallIntegerField(null=True)),
                ('departement', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
