# Generated by Django 3.1.8 on 2021-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doses', '0002_dosescentre'),
        ('vaccin', '0001_initial'),
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreambulatoire',
            name='vaccins',
            field=models.ManyToManyField(through='doses.DosesCentre', to='vaccin.Vaccin'),
        ),
    ]
