# Generated by Django 3.1.8 on 2021-04-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_auto_20210424_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centreambulatoire',
            old_name='id_ministere',
            new_name='gid',
        ),
    ]
