# Generated by Django 3.1.8 on 2021-04-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClesDepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_de_derniere_modification', models.DateTimeField(auto_now=True)),
                ('date_de_validation_provisoire', models.DateTimeField()),
                ('date_de_validation', models.DateTimeField()),
                ('numero_injection', models.CharField(choices=[('1', 1), ('2', 2)], default='1', max_length=1)),
                ('nb_doses', models.PositiveSmallIntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centre.centreambulatoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
