# Generated by Django 3.1.8 on 2021-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClesDepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.PositiveSmallIntegerField(null=True)),
                ('code_commune_insee', models.PositiveSmallIntegerField(null=True)),
                ('date_de_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_de_derniere_modification', models.DateTimeField(auto_now=True)),
                ('date_de_validation_provisoire', models.DateTimeField(null=True)),
                ('date_de_validation', models.DateTimeField(null=True)),
                ('semaine_de_vaccination', models.PositiveSmallIntegerField(null=True)),
                ('numero_injection', models.CharField(choices=[(1, '1'), (2, '2')], default=(1, '1'), max_length=1)),
                ('numero_departement', models.CharField(choices=[(1, '01 - Ain'), (2, '02 - Aisne'), (3, '03 - Allier'), (4, '04 - Alpes-de-Haute-Provence'), (5, '05 - Hautes-Alpes'), (6, '06 - Alpes-Maritimes'), (7, '07 - Ardèche'), (8, '08 - Ardennes'), (9, '09 - Ariège'), (10, '10 - Aube'), (11, '11 - Aude'), (12, '12 - Aveyron'), (13, '13 - Bouches-du-Rhône'), (14, '14 - Calvados'), (15, '15 - Cantal'), (16, '16 - Charente'), (17, '17 - Charente-Maritime'), (18, '18 - Cher'), (19, '19 - Corrèze'), (20, '2A - Corse-du-Sud'), (21, '2B - Haute-Corse'), (22, "21 - Côte-d'Or"), (23, "22 - Côtes d'Armor"), (24, '23 - Creuse'), (25, '24 - Dordogne'), (26, '25 - Doubs'), (27, '26 - Drôme'), (28, '27 - Eure'), (29, '28 - Eure-et-Loir'), (30, '29 - Finistère'), (31, '30 - Gard'), (32, '31 - Haute-Garonne'), (33, '32 - Gers'), (34, '33 - Gironde'), (35, '34 - Hérault'), (36, '35 - Ille-et-Vilaine'), (37, '36 - Indre'), (38, '37 - Indre-et-Loire'), (39, '38 - Isère'), (40, '39 - Jura'), (41, '40 - Landes'), (42, '41 - Loir-et-Cher'), (43, '42 - Loire'), (44, '43 - Haute-Loire'), (45, '44 - Loire-Atlantique'), (46, '45 - Loiret'), (47, '46 - Lot'), (48, '47 - Lot-et-Garonne'), (49, '48 - Lozère'), (50, '49 - Maine-et-Loire'), (51, '50 - Manche'), (52, '51 - Marne'), (53, '52 - Haute-Marne'), (54, '53 - Mayenne'), (55, '54 - Meurthe-et-Moselle'), (56, '55 - Meuse'), (57, '56 - Morbihan'), (58, '57 - Moselle'), (59, '58 - Nièvre'), (60, '59 - Nord'), (61, '60 - Oise'), (62, '61 - Orne'), (63, '62 - Pas-de-Calais'), (64, '63 - Puy-de-Dôme'), (65, '64 - Pyrénées-Atlantiques'), (66, '65 - Hautes-Pyrénées'), (67, '66 - Pyrénées-Orientales'), (68, '67 - Bas-Rhin'), (69, '68 - Haut-Rhin'), (70, '69 - Rhône'), (71, '70 - Haute-Saône'), (72, '71 - Saône-et-Loire'), (73, '72 - Sarthe'), (74, '73 - Savoie'), (75, '74 - Haute-Savoie'), (76, '75 - Paris'), (77, '76 - Seine-Maritime'), (78, '77 - Seine-et-Marne'), (79, '78 - Yvelines'), (80, '79 - Deux-Sèvres'), (81, '80 - Somme'), (82, '81 - Tarn'), (83, '82 - Tarn-et-Garonne'), (84, '83 - Var'), (85, '84 - Vaucluse'), (86, '85 - Vandée'), (87, '86 - Vienne'), (88, '87 - Haute-Vienne'), (89, '88 - Vosges'), (90, '89 - Yonne'), (91, '90 - Territoire de Belfort'), (92, '91 - Essonne'), (93, '92 - Hauts-de-Seine'), (94, '93 - Seine-St-Denis'), (95, '94 - Val-de-Marne'), (96, "95 - Val-D'Oise"), (97, '971 - Guadeloupe'), (98, '972 - Martinique'), (99, '973 - Guyane'), (100, '974 - La Réunion'), (101, '976 - Mayotte')], default=(1, '01 - Ain'), max_length=3)),
                ('nb_doses', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
