# Generated by Django 3.1.8 on 2021-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doses', '0001_initial'),
        ('vaccin', '0001_initial'),
        ('cles_departement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clesdepartement',
            name='vaccins',
            field=models.ManyToManyField(through='doses.DosesDepartement', to='vaccin.Vaccin'),
        ),
    ]
