# Generated by Django 3.1.8 on 2021-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cles_departement', '0002_clesdepartement_vaccins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clesdepartement',
            name='nb_doses',
        ),
        migrations.RemoveField(
            model_name='clesdepartement',
            name='numero_injection',
        ),
    ]
