# Generated by Django 3.1.8 on 2021-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cles_departement', '0003_auto_20210424_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clesdepartement',
            name='date_de_validation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clesdepartement',
            name='date_de_validation_provisoire',
            field=models.DateTimeField(null=True),
        ),
    ]
