# Generated by Django 3.1.8 on 2021-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cles_departement', '0007_auto_20210424_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='clesdepartement',
            name='semaine_de_vaccination',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
