# Generated by Django 3.1.8 on 2021-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cles_departement', '0008_clesdepartement_semaine_de_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='clesdepartement',
            name='code_commune_insee',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clesdepartement',
            name='code_postal',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
