# Generated by Django 3.1.8 on 2021-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('intervalle_injections', models.PositiveSmallIntegerField(default=28)),
            ],
        ),
    ]
