# Generated by Django 3.1.8 on 2021-04-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccin',
            name='nb_par_flacon',
        ),
    ]
