# Generated by Django 3.1.8 on 2021-04-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
        ('vaccin', '0001_initial'),
        ('doses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosesCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_doses', models.PositiveSmallIntegerField(default=0)),
                ('nb_doses_par_flacon', models.PositiveSmallIntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.centreambulatoire')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccin.vaccin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
