# Generated by Django 3.1.8 on 2021-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosesdepartement',
            name='nb_doses_par_flacon',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosesregion',
            name='nb_doses_par_flacon',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
