# Generated by Django 3.1.8 on 2021-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doses', '0002_dosescentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosescentre',
            name='numero_injection',
            field=models.CharField(choices=[(1, '1'), (2, '2')], default=(1, '1'), max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dosesdepartement',
            name='numero_injection',
            field=models.CharField(choices=[(1, '1'), (2, '2')], default=(1, '1'), max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dosesregion',
            name='numero_injection',
            field=models.CharField(choices=[(1, '1'), (2, '2')], default=(1, '1'), max_length=1, null=True),
        ),
    ]
